export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/cart'
export const PRODUCT_ROUTE = '/product'
export const HOME_ROUTE = '/'
export const UI_KIT = '/ui-kit'
